<?php

/**
 * @file
 * reservations_preset_end functions
 */

/**
 * Implements hook_init().
 */
function reservations_preset_end_init() {
  drupal_add_css(drupal_get_path('module', 'reservations_preset_end') . '/reservations_preset_end.css');
  //drupal_add_js(drupal_get_path('module', 'reservations_preset_end') . '/reservations_preset_end.js');
}

/**
 * Implementation of hook_menu().
 */
function reservations_preset_end_menu() {
  $items = array();

  $items['admin/config/reservations/preset-end'] = array(
    'title' => 'Preset End Configuration',
    'description' => 'Configuration number of hours added to the start time.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reservations_preset_end_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
    
  return $items;
}

/**
 * Builds the cm_project admininstration settings form.
 */
function reservations_preset_end_admin_settings($form, &$form_state) {
  $form = array();
  
   $form['reservations_preset_end_hours'] = array(
    '#type' => 'textfield',
    '#title' => t('Hours after reservation start that the reservation automatically end'),
    '#size' => 11,
    '#maxlength' => 11,
    '#default_value' => variable_get('reservations_preset_end_hours', '1'),
    '#description' => t('All validation still applies.  If the hours of operation end at 5PM and a user starts a reservations at 4:30, that will fail.'),
  );
 
  return system_settings_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reservations_preset_end_form_reservations_reservation_node_form_alter(&$form, &$form_state) {
 
 // unsetting this removes the field.  The checkbox to readd the field is hidden by CSS
 // @TODO: is that checkbox exposed to somewhere so we aren't relying on CSS?
 unset($form['field_reservations_date'][LANGUAGE_NONE][0]['#default_value']['value2']);

}

function reservations_preset_end_node_presave($node) {

  //number of hours to adjust in seconds
  $adjust_by = 60*60*variable_get('reservations_preset_end_hours', '1');
  
  // add the seconds to the start time
  $adjusted_time = strtotime($node->field_reservations_date[LANGUAGE_NONE][0]['value']) + $adjust_by;
  
  //format as 2013-02-19 17:30:00
  $node->field_reservations_date[LANGUAGE_NONE][0]['value2'] = date("Y-m-d H:i:s", $adjusted_time);
  
}